name: cd
on:
  workflow_run:
    workflows:
    - ci
    branches:
    - main 
    types:
    - completed
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: print if skip 
        if: contains(toJson(github.event.commits.*.message),  '#skip')
        run: echo "skip is in message" 
      - name: print if not skip 
        if: ${{!contains(toJson(github.event.commits.*.message),  '#skip')}}
        run: echo "skip is not in message" 
      - name: Trigger Render deploy
        if: ${{!contains(toJson(github.event.commits.*.message),  '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }} 
