name: cd
on:
  workflow_run:
    workflows:
    - ci
    branches:
    - main 
    types:
    - completed
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render deploy
        if: |
          github.event.workflow_run.conclusion == 'success' &&
            ${{!contains(toJson(github.event.commits.*.message),  '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }} 
