name: cd
on:
  workflow_run:
    workflows:
    - ci
    branches:
    - main 
    types:
    - completed
jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
        ${{!contains(toJson(github.event.commits.*.message),  '#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger Render deploy
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }} 
