name: cd
on:
  workflow_run:
    workflows:
      - ci
    branches:
      - main
    types:
      - completed
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
        fetch-depth: 0
      - name: Trigger Render deploy
        if: ${{!contains(toJson(github.event.workflow_run.head_commit.message),  '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
