name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm ci 
      - run: npm run eslint
      - run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run build-start-prod
          wait-on: http://localhost:5001
        
