name: discord deploy message 
on:
  workflow_run:
    workflows:
    - cd
    types:
    - completed
jobs:

  on-success:
    if: success()
    name: Successful Deploy 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Message discord on deploy success
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          details: Deploy Succeeded by emadkhan
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

