name: message-discord 

on:
  workflow_run:
    workflows:
      - cd
      - ci
      - health-check
    types:
      - completed

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub workflow 
        env:
          GITHUB_WORKFLOW: ${{ toJson(github.event.workflow) }}
        run: echo "$GITHUB_WORKFLOW"
      - name: Dump GitHub workflow run
        env:
          GITHUB_RUN: ${{ toJson(github.event.workflow_run) }}
        run: echo "$GITHUB_RUN"
      - name: Test direct access
        run: echo ${{github.event.workflow_run}}
      - name: Test direct access with toJSon
        run: echo ${{toJson(github.event.workflow_run)}}
  on-deploy-success:
    name: Successful Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Message discord on deploy success
        uses: rjstone/discord-webhook-notify@v1
        if: github.event.workflow == 'cd' && github.event.workflow_run.conclusion == 'success'
        with:
          severity: info
          details: Deploy succeeded
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  on-build-failure:
    name: Failed Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Message discord on build failure 
        uses: rjstone/discord-webhook-notify@v1
        if: github.event.workflow == 'ci' && github.event.workflow_run.conclusion == 'failure'
        with:
          severity: error
          details: Build failed 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
  on-health-check-failure:
    name: Failed Health Check 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Message discord on health check failure 
        uses: rjstone/discord-webhook-notify@v1
        if: github.event.workflow == 'health-check' && github.event.workflow_run.conclusion == 'failure'
        with:
          severity: error
          details: Health check failed 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

