name: message-discord 

on:
  workflow_run:
    workflows:
      - cd
      - ci
      - health-check
    types:
      - completed

jobs:
  on-deploy-success:
    name: Successful Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - if: github.event.workflow == 'cd' && github.event.workflow_run.conclusion == 'success'
      - name: Message discord on deploy success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Deploy succeeded
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  on-build-failure:
    name: Failed Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - if: github.event.workflow == 'ci' && github.event.workflow_run.conclusion == 'failure'
      - name: Message discord on build failure 
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Build failed 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
  on-health-check-failure:
    name: Failed Health Check 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - if: github.event.workflow == 'health-check' && github.event.workflow_run.conclusion == 'failure'
      - name: Message discord on build failure 
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Health check failed 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

