name: discord build message 
on:
  workflow_run:
    workflows:
    - ci
    types:
    - completed

jobs:
  on-failure:
    if: failure()
    name: Failed Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Message discord on build failure 
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: error
          details: Deploy Succeeded by emadkhan
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
