name: Deploy pipeline

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install
  lint:
    needs: setup
    steps:
      - run: npm run eslint
  test:
    needs: setup
    steps:
      - run: npm run test
        
